### ISSUE TITLE
Delay Time

### ISSUE THREAD

**Issue by aponkz** [PPartisan/Simple-Alarms#10]
after compile and success, im testing the alarm, but delay +- 20 second every time. 
testing on ZTE, Mi Max 2, Redmi Note 4, and Redmi Note 1w.

**Comment by PPartisan** [comment]
Are you expecting the alarm to sound as soon as the minute changes? If so, then that is not expected behaviour. The time the alarm goes off is relative to the time the alarm was set.

For example, if you set an alarm at 9:31:40 to go off at 9:32, then the alarm will go off at 9:32:40. If you set an alarm at 9:31:20 to go off at 9:32, then it will go off at 9:32:20.

Does this make sense?

If you want to change this behaviour, I expect you could achieve it by modifying the following lines in `AddEditAlarmFragment`:
```
final Calendar time = Calendar.getInstance();
//time.set(Calendar.SECOND, 0); <-- Add this line
time.set(Calendar.MINUTE, ViewUtils.getTimePickerMinute(mTimePicker));
time.set(Calendar.HOUR_OF_DAY, ViewUtils.getTimePickerHour(mTimePicker));
alarm.setTime(time.getTimeInMillis());
```

**Comment by aponkz** [comment]
ok thankyou PPartisan, i will try to add time.set calendar.SECOND, 0.
issue is closed now
