### ISSUE TITLE
Questions about Saving Alarm

### ISSUE THREAD

**Issue by JisooKK** [PPartisan/Simple-Alarms#12]
Hello sir.
It should only be saved when the Save button is pressed, but the alarm is saved when other buttons  (For example: Back button) are pressed.Is it a bug?

**Comment by PPartisan** [comment]
Hello,

It depends on how you mean. The expected behaviour is that when you press the "+" Floating Action Button to create a new Alarm, a new alarm is created immediately and you are then taken to a page where you can edit its details. If you make changes to the alarm but don't press save, then those changes will not be saved, but the Alarm that was newly created still exists.

So, here are two scenarios where you may edit an alarm, and the expected behaviour:
 
(1) Pressing the "+" Button creates a new Alarm immediately, and takes you to an "edit alarm" page.
  (1a) Pressing back now will return you to your Alarm list screen, where the new alarm will exist. This new alarm exists even though you didn't press Save, as it has already been created.
  (1b) Making changes on this edit screen and then pressing back without first pressing Save will take you back to your Alarm list screen. The edits you made will not exist, but the alarm you created will.
  (1c) Making changes on this edit screen and then pressing Save and then pressing back will take you back to your Alarm list screen. The edits you made will have been persisted.

(2) Pressing on an existing alarm in the Alarms list will take you to its edit page.
  (2a) Making changes and then pressing back without pressing save will not persists those changes. The alarm will be as it was before you launched the edit alarm page.
  (2b) Making changes, pressing save and then pressing back will persist those changes.

If you see anything other than this happening then it should be considered a bug!

**Comment by PPartisan** [comment]
I'm going to close this as I assume this was more a question on current app functionality than a bug. If you encounter a scenario that doesn't meet the bullet points I listed in my previous comment, then let me know and I can investigate it.
